homepage/urls.py
from django.urls import path
from . import views

app_name ='swifri'
urlpatterns =[
    path('', views.IndexView.as_view(), name='index'),
    path('art_list', views.Art_List_View.as_view(), name='art_list'),
    path('art_detail/<uuid:pk>', views.Art_Detail_View.as_view(), name='art_detail'),
]

swifrihomepage/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_title = 'SwiFri'
admin.site.site_header = 'SwiFri'
admin.site.index_title = 'Menu'
urlpatterns = [
    path('youlookslikeadmin/', admin.site.urls),
    path('', include('homepage.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
import uuid

# CustomUserは自分以外は変更できない。
class CustomUser(AbstractUser):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    phone = models.PositiveIntegerField(null=True)
    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email',]
    #
    # class Meta:
    #     verbose_name_plural= 'CustomUser'

homepage/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
import uuid

def image_directory_path(instance, filename):
    return 'images/{}.{}'.format(str(uuid.uuid4()), filename.split('.')[-1])

class Art(models.Model):
    id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
    title = models.CharField(max_length=100, verbose_name='title')
    date = models.DateTimeField(auto_now_add=True, verbose_name='date')
    image = models.ImageField(upload_to=image_directory_path, verbose_name='image')
    description = models.TextField(null=True, blank=True, verbose_name='description')

    class Meta:
        verbose_name_plural='Art'

    def __str__(self):
        return self.title


# class Movie(models.Model):
#     url = models.URLField()
#
#     class Meta:
#         verbose_name_plural='Movie'
#
#
# class Music():
#     url = models.URLField()
#
#     class Meta:
#         verbose_name_plural = 'Music'

accounts/views.py
from django.shortcuts import render

# Create your views here.

homepage/views.py
from django.shortcuts import render
from django.views import generic
from .models import Art

class IndexView(generic.TemplateView):
    template_name = 'index.html'

class Art_List_View(generic.ListView):
    template_name = './art/list.html'
    model = Art
    ordering = ['-date']

class Art_Detail_View(generic.DetailView):
    template_name = './art/detail.html'
    model = Art

templates/art/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Art{% endblock%}
{% block content %}
    <div class="content">
        <div class="art-detail-area">
            <ul>
                <li class="art-detail-image">
                    <img src="{{ art.image.url }}">
                </li>
                <li class="art-detail-title">
                    <h1>{{ art.title }}</h1>
                </li>
                <li class="art-detail-date">
                    <p>{{ art.date|date:"Y.n.j" }}</p>
                </li>
                <li class="art-detail-description">
                    <h3>{{ art.description| linebreaksbr }}</h3>
                </li>
            </ul>
        </div>
    </div>
{% endblock %}

templates/art/list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Art{% endblock%}
{% block content %}
    <div class="content">
        <div class="art-list-area">
            {% for object in object_list %}
                <div class="art-list-item">
                    <a href="{% url 'swifri:art_detail' pk=object.pk %}">
                        <img src="{{ object.image.url }}">
                        <h3>{{ object.title }}</h3>
                    </a>
                </div>
                {% endfor %}
        </div>
    </div>
{% endblock %}

templates/base.html
{% load static %}
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport", content="width=device-width, initial-scale=1, minium-scale=1, user-scale-able=yes " >
        <link rel="stylesheet", type="text/css", href="{% static 'css/mystyle.css' %}">
        <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body>
        <header>
            <div class="header-content">
                <div class="swifri">
                    <h1 class="h1-swifri"><a href="{% url 'swifri:index' %}">Swifri</a></h1>
                </div>
                <div class="sns-accounts">
                    <a href="https://twitter.com/SwiFri" target="_blank" rel="noopener noreferrer">
                        <i class="fab fa-twitter"></i>
                    </a>
                    <a href="https://www.instagram.com/swifri_/" target="_blank" rel="noopener noreferrer">
                        <i class="fab fa-instagram"></i>
                    </a>
                    <a href="https://opensea.io/SwiFri"target="_blank" rel="noopener noreferrer">
                        <i class="fab fa-bitcoin"></i>
                    </a>
                </div>
            </div>

        </header>

        {% block content %}{% endblock %}

        <footer>
            <div>
                <h1></h1>
            </div>
        </footer>
    </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Top{% endblock%}
{% block content %}
    <div class="content">
        <ul class="three-key">
            <li>
                <a href="#">
                    <h3>MOVIE</h3>
                </a>
            </li>
            <li>
                <a href="{% url 'swifri:art_list' %}">
                    <h3>ART</h3>
                </a>
            </li>
            <li>
                <a href="#">
                    <h3>MUSIC</h3>
                </a>
            </li>
        </ul>
        
        <div class="about">
            <img src="{% static 'images/inside_woman.jpg' %}">
        </div>
        <div class="intro">
            <h2>
                We design from the past.
            </h2>
            <h4>
                We create the movie, art, music by artificial intelligence.<br>
                Enjoy my work !!<br>
                *Sorry, As of now, only art.<br>
            </h4>

        </div>

    </div>
{% endblock %}